<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:16:40.
 */
class fileResourceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var fileResource
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new fileResource;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers fileResource::getInstanceOf
     * @todo   Implement testGetInstanceOf().
     */
    public function testGetInstanceOf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers fileResource::GetFileContent
     * @todo   Implement testGetFileContent().
     */
    public function testGetFileContent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers fileResource::dropFile
     * @todo   Implement testDropFile().
     */
    public function testDropFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers fileResource::savefile
     * @todo   Implement testSavefile().
     */
    public function testSavefile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers fileResource::append
     * @todo   Implement testAppend().
     */
    public function testAppend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers fileResource::ShiftAndAproximado
     * @todo   Implement testShiftAndAproximado().
     */
    public function testShiftAndAproximado() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers fileResource::download
     * @todo   Implement testDownload().
     */
    public function testDownload() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers fileResource::FindTextInPDF
     * @todo   Implement testFindTextInPDF().
     */
    public function testFindTextInPDF() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers fileResource::GetPalavrasMaisRepetidas
     * @todo   Implement testGetPalavrasMaisRepetidas().
     */
    public function testGetPalavrasMaisRepetidas() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers fileResource::display_filesize
     * @todo   Implement testDisplay_filesize().
     */
    public function testDisplay_filesize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
