<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:16:38.
 */
class VideoConverterTest extends PHPUnit_Framework_TestCase {

    /**
     * @var VideoConverter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new VideoConverter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers VideoConverter::setVideoFile
     * @todo   Implement testSetVideoFile().
     */
    public function testSetVideoFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers VideoConverter::video2mobile
     * @todo   Implement testVideo2mobile().
     */
    public function testVideo2mobile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers VideoConverter::video2flash
     * @todo   Implement testVideo2flash().
     */
    public function testVideo2flash() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers VideoConverter::video2html5
     * @todo   Implement testVideo2html5().
     */
    public function testVideo2html5() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers VideoConverter::download
     * @todo   Implement testDownload().
     */
    public function testDownload() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
