<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:16:34.
 */
class CsvTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Csv
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Csv;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Csv::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csv::getSum
     * @todo   Implement testGetSum().
     */
    public function testGetSum() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csv::getMedia
     * @todo   Implement testGetMedia().
     */
    public function testGetMedia() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csv::getAllLines
     * @todo   Implement testGetAllLines().
     */
    public function testGetAllLines() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csv::getNumberOfLines
     * @todo   Implement testGetNumberOfLines().
     */
    public function testGetNumberOfLines() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csv::getNextLine
     * @todo   Implement testGetNextLine().
     */
    public function testGetNextLine() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csv::getCurrentLine
     * @todo   Implement testGetCurrentLine().
     */
    public function testGetCurrentLine() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csv::getHeader
     * @todo   Implement testGetHeader().
     */
    public function testGetHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csv::removeColum
     * @todo   Implement testRemoveColum().
     */
    public function testRemoveColum() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csv::filtherColuns
     * @todo   Implement testFiltherColuns().
     */
    public function testFiltherColuns() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csv::arrayToCsv
     * @todo   Implement testArrayToCsv().
     */
    public function testArrayToCsv() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Csv::save
     * @todo   Implement testSave().
     */
    public function testSave() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
